### ISSUE TITLE
Source Code Question

### ISSUE THREAD

**Issue by carpben** [AnatoliyGatt/deep-freeze-node#6]
In deepFreeze.js, lines 24-25: 

    for (propertyKey in object) {
        if (object.hasOwnProperty(propertyKey)) {

What's the porpose of the if statement? propertyKey is a propertyKey is a property key of object, which is also enumerable. In which cases will it return false?

**Comment by danieladams456** [comment]
It will skip properties inherited from any parent objects in the prototype chain.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty
